spring.application.name=ResumePrasing


# Server configuration
server.port=8082

# Database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/kysz_interview
spring.datasource.username=${username}
spring.datasource.password=${password}


# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Logging
logging.level.org.springframework=INFO
logging.level.com.aiinterview=DEBUG

# Jackson
spring.jackson.serialization.write-dates-as-timestamps=false


spring.ai.openai.api-key=${spring.ai.openai.api-key}
spring.ai.openai.model=${spring.ai.openai.model}
spring.ai.openai.embedding.api=${spring.ai.openai.api-key}
ai.openai.embedding.base-url=https://api.openai.com

# CORS configuration
spring.mvc.cors.allowed-origins=http://localhost:3000
spring.mvc.cors.allowed-methods=GET,POST,PUT,DELETE
spring.mvc.cors.allowed-headers=*